# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCMjXIpcAvsPXlxEgb3OPGraoIaIgZtc
"""

import pandas as pd
train=pd.read_csv('/content/train.csv').drop(columns='Survived')
test=pd.read_csv('/content/test.csv')

df=pd.concat([train,test])
#len(df)
df.head(1)

pop_male=df[df['Sex']=='male']['Age'].dropna()
pop_female=df[df['Sex']=='female']['Age'].dropna()

samp_male=pop_male.sample(25)
samp_female=pop_female.sample(25)

alpha = 0.05
# H0 - Mean age of male and female are similar
# H1 - Mean age of male is higher than female

from scipy.stats import shapiro

# Perform the Shapiro-Wilk test for both desktop and mobile users
shapiro_male = shapiro(samp_male)
shapiro_female = shapiro(samp_female)

print("Shapiro-Wilk test for desktop users:", shapiro_male)
print("Shapiro-Wilk test for mobile users:", shapiro_female)



from scipy.stats import levene

levene_test=levene(samp_male,samp_female)
levene_test

import  scipy.stats as stats


t_statistics,p_value=stats.ttest_ind(samp_male,samp_female)

t_statistics,(p_value/2)

alpha=0.05

if (p_value/2) < alpha :
  print('reject the null hypothesis ')

else:
  print('fail to reject the null hypothesis')